### ISSUE TITLE
Prevent proposal spam by allowing maximum 10 proposals per proposer

### ISSUE THREAD

**Issue by errows** [eoscanada/eosio.forum#17]

**Comment by abourget** [comment]
What is proposal spam? I don't think it makes sense to limit the number of proposal.

Avoiding spam simply means selecting accounts that propose things.

It makes sense to do a referendum only if you can follow through and apply it's results, so I don't see value in letting "anyone" submit referendum questions for general question. Questions will be diligently crafted by those bodies trying to poll their users.

That's why it makes sense to only list major accounts or community accounts (like eosio, everipedia, monstereosio, etc..). If someone wants to participate in the referendum for a given community, they should find their way to the right scope of proposals. That'll be done through out of band communications in any case.

**Comment by maoueh** [comment]
Right now, in the current form, anybody can spam the `propose` action with meaningless content. The discussion to have is how can we avoid that.

Having a hard limit on proposal would indeed limit number of proposals that can be submitted. I don't think it will ever happen someone will find the need to submit more than a certain number of proposals. But is indeed not a silver bullet.

Should we add a `require_auth(_self)` in the propose function (in addition to the `proposer` already present) so that only some specific set of person can propose stuff? Will need to gather more feedback from the community if we go this way. But that would fit nicely with how EEP would be merged in the repository that would be managed by volunteer.

In fact, the team managing the repo could also manage the proposals.

**Comment by maoueh** [comment]
Seems it's not something of importance right now, will see later.
